### ISSUE TITLE
Les fiches commençant par un nombre ne sont pas lues dans le dépot ?

### ISSUE THREAD

**Issue by vinber** [multibao/site#2]
La fiche http://www.multibao.org/infolab-cd33/datalunch/0-index.md n'est pas visible dans le dépot http://www.multibao.org/infolab-cd33/datalunch/

**Comment by WolffThomas** [comment]
Bonjour Vincent,

de mon côté elle y apparaît (en pièce jointe capture d'écran).

En est-il toujours de même de ton côté ?

Thomas

**Comment by vinber** [comment]
et bien oui :(

![multibao-datalunch](https://cloud.githubusercontent.com/assets/890869/12220940/7143e874-b786-11e5-9d08-43594dbd0bc6.png)

**Comment by WolffThomas** [comment]
Salut Vincent,

  * Possibilité 1: en regardant la copie d'écran que tu m'as envoyé, je
    me suis rendu compte qu'il y avait 4 lignes de noms de dépôt. Il est
    possible que cette 4ème ligne de nom de dépôts ... couvre ton fichier.
      o pourrais tu dézommer sur la page ? Le fichier apparaît-il ?
      o j'ai créé 2 fichiers commençant par des chiffres dans mon dépôt
        <http://www.multibao.org/wolffthomas/perles_gestion_projets/contributions>,
        les vois tu apparaître?
  * Possibilité 2: il y a déjà eu des soucis avec le navigateur Safari;
    est-ce celui que tu utilises?

  On va trouver ;) !

Thomas

**Comment by vinber** [comment]
Bonjour, tu as trouvé, c'est bien la quatrième ligne qui cache.
Quelques tests montrent que dans mon cas : 
- le mode normal Ctrl+0 je ne vois pas le 0-index
- si je zoome, je ne vois pas
- si je dézoome, alors je vois apparraitre, puis il se recache !!!

Non je n'utiise pas Safari, mais Firefox 43 sur ubuntu (je le précise car j'ai ce souci sur 2 ordi avec cette config!!!)

**Comment by vinber** [comment]
Et sur les tests que tu as fait sur ton dépôt, je confirme que je vois le 1_test et que le 0-test apparait selon le niveau de zoom.

Encore merci
