### ISSUE TITLE
Problèm affichage première fiche

### ISSUE THREAD

**Issue by RomainLalande** [multibao/site#3]
Bonjour,

Dans chaque dépot affiché sur multibao, la prmeière fiche n'apparaît pas. Comme c'est souvent le readme, ça ne se remarque pas trop, mais ce peut être gênant.

on peut tout de même cliquer dessus, mais on ne vois pas le texte.

**Comment by WolffThomas** [comment]
Merci Romain de faire remonter le problème.

  * Quentin (swergas) a proposé la correction de ce problème la semaine
    dernière: https://github.com/multibao/contributions/pull/6
  * je viens de la valider à l'instant
  * Romain, pourrais tu valider que c'est bon?

Merci beaucoup Quentin !

Thomas

**Comment by RomainLalande** [comment]
C'est parfait !
